services:
  app:
    image: dptsjdb:1.6
    build: .
    container_name: dptsjdb-1.6
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
